import { AgentTemplate } from "../../types";

export const AGENT_TEMPLATES: AgentTemplate[] = [
  // {
  //   id: "hybrid-patrol",
  //   name: "综合巡检 Agent",
  //   description: "面向离线图片、音频和实时监控的综合巡检模版，适合做现场异常融合研判。",
  //   agents: ["总控调度 Agent", "异常识别 Agent", "风险汇总 Agent"],
  //   videoLibraries: ["现场视频事件库", "监控目标检测库"],
  //   imageLibraries: ["巡检图像缺陷库", "异常样例图片库"],
  //   audioLibraries: ["设备异响样本库", "环境噪声特征库"],
  //   tools: ["风险评估工具", "结构化报告工具", "告警摘要工具"],
  //   supportedModes: ["offline", "realtime"],
  //   defaultNodeFlow: [
  //     {
  //       id: "node-a",
  //       nodeName: "A 节点",
  //       role: "调用视频能力完成实时场景扫描",
  //       resourceType: "videoLibrary",
  //       resourceName: "现场视频事件库",
  //     },
  //     {
  //       id: "node-b",
  //       nodeName: "B 节点",
  //       role: "调用图片能力完成异常目标比对",
  //       resourceType: "imageLibrary",
  //       resourceName: "巡检图像缺陷库",
  //     },
  //     {
  //       id: "node-c",
  //       nodeName: "C 节点",
  //       role: "调用工具完成风险归并与结论输出",
  //       resourceType: "tool",
  //       resourceName: "风险评估工具",
  //     },
  //   ],
  //   defaultSummary: "聚合多源素材，输出现场异常、风险等级和后续处置建议。",
  // },
  {
    id: "video-patrol",
    name: "视频巡检 Agent",
    description: "偏重实时监控巡检，适合监控流目标检测、行为识别和关键帧提取。",
    agents: ["视频巡视 Agent", "事件抓取 Agent"],
    videoLibraries: ["实时监控分析库", "轨迹识别库"],
    imageLibraries: ["关键帧复核图片库"],
    audioLibraries: [],
    tools: ["事件时间轴工具", "巡检快照工具"],
    supportedModes: ["offline", "realtime"],
    defaultNodeFlow: [
      {
        id: "node-a",
        nodeName: "A 节点",
        role: "调用视频库分析实时监控画面",
        resourceType: "videoLibrary",
        resourceName: "实时监控分析库",
      },
      {
        id: "node-b",
        nodeName: "B 节点",
        role: "调用图片库复核关键帧目标",
        resourceType: "imageLibrary",
        resourceName: "关键帧复核图片库",
      },
      {
        id: "node-c",
        nodeName: "C 节点",
        role: "调用工具生成事件时间线",
        resourceType: "tool",
        resourceName: "事件时间轴工具",
      },
    ],
    defaultSummary: "从实时监控流中提取关键事件，输出关键时间点和风险提示。",
  },
  {
    id: "image-inspector",
    name: "图像研判 Agent",
    description: "适合离线图片和现场拍摄内容的细节核验、缺陷定位与多图比对。",
    agents: ["图像识别 Agent", "细节比对 Agent"],
    videoLibraries: [],
    imageLibraries: ["图像特征样本库", "缺陷位置图库"],
    audioLibraries: [],
    tools: ["图像标注工具", "结果归档工具"],
    supportedModes: ["offline", "realtime"],
    defaultNodeFlow: [
      {
        id: "node-a",
        nodeName: "A 节点",
        role: "调用图片库完成初筛与目标检出",
        resourceType: "imageLibrary",
        resourceName: "图像特征样本库",
      },
      {
        id: "node-b",
        nodeName: "B 节点",
        role: "调用图片库完成缺陷位置复核",
        resourceType: "imageLibrary",
        resourceName: "缺陷位置图库",
      },
      {
        id: "node-c",
        nodeName: "C 节点",
        role: "调用工具输出结构化标注结果",
        resourceType: "tool",
        resourceName: "图像标注工具",
      },
    ],
    defaultSummary: "面向现场图片与拍照内容，输出目标识别、缺陷定位和标注结论。",
  },
  {
    id: "audio-diagnosis",
    name: "音频异常诊断 Agent",
    description: "适合现场录音、设备异响和环境异常声音分析。",
    agents: ["声学诊断 Agent", "告警归因 Agent"],
    videoLibraries: [],
    imageLibraries: [],
    audioLibraries: ["设备异响谱库", "环境报警声音库"],
    tools: ["频谱分析工具", "告警归因工具"],
    supportedModes: ["offline", "realtime"],
    defaultNodeFlow: [
      {
        id: "node-a",
        nodeName: "A 节点",
        role: "调用音频库提取声学特征",
        resourceType: "audioLibrary",
        resourceName: "设备异响谱库",
      },
      {
        id: "node-b",
        nodeName: "B 节点",
        role: "调用音频库匹配报警模式",
        resourceType: "audioLibrary",
        resourceName: "环境报警声音库",
      },
      {
        id: "node-c",
        nodeName: "C 节点",
        role: "调用工具完成异常归因输出",
        resourceType: "tool",
        resourceName: "告警归因工具",
      },
    ],
    defaultSummary: "结合录音内容完成异响识别、告警归因与处理建议输出。",
  },
];
